version = 0.1

[default.deploy.parameters]
stack_name = "flight-booking-api"
resolve_s3 = true
s3_prefix = "flight-booking-api"
region = "eu-north-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "eu-north-1"
